services:
  dagster_postgresql:
    image: postgres:11
    container_name: dagster_postgresql
    environment:
      POSTGRES_USER: "postgres_user"
      POSTGRES_PASSWORD: "postgres_password"
      POSTGRES_DB: "postgres_db"
    networks:
      - dagster_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_user -d postgres_db"]
      interval: 10s
      timeout: 8s
      retries: 5

  dagster_assets:
    build:
      context: ./dagster
      dockerfile: ./assets.Dockerfile
      args:
        - PYTHON_VERSION=3.9-slim
    container_name: dagster_assets
    image: dagster_assets
    restart: always
    environment:
      DAGSTER_POSTGRES_USER: "postgres_user"
      DAGSTER_POSTGRES_PASSWORD: "postgres_password"
      DAGSTER_POSTGRES_DB: "postgres_db"
      DAGSTER_CURRENT_IMAGE: "dagster_assets"
    volumes:
      - ./dagster/:/opt/dagster/app
    networks:
      - dagster_network

  dagster_webserver:
    build:
      context: ./dagster
      dockerfile: ./dagster.Dockerfile
      args:
        - PYTHON_VERSION=3.9-slim
    entrypoint:
      - dagster-webserver
      - -h
      - "0.0.0.0"
      - -p
      - "3000"
      - -w
      - workspace.yaml
    container_name: dagster_webserver
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      DAGSTER_POSTGRES_USER: "postgres_user"
      DAGSTER_POSTGRES_PASSWORD: "postgres_password"
      DAGSTER_POSTGRES_DB: "postgres_db"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
      # - ./dagster/orchestrator/assets/:/opt/dagster/dagster_home/assets/
    networks:
      - dagster_network
    depends_on:
      dagster_postgresql:
        condition: service_healthy
      dagster_assets:
        condition: service_started

  dagster_daemon:
    build:
      context: ./dagster
      dockerfile: ./dagster.Dockerfile
      args:
        - PYTHON_VERSION=3.9-slim
    entrypoint:
      - dagster-daemon
      - run
    container_name: dagster_daemon
    restart: on-failure
    environment:
      DAGSTER_POSTGRES_USER: "postgres_user"
      DAGSTER_POSTGRES_PASSWORD: "postgres_password"
      DAGSTER_POSTGRES_DB: "postgres_db"

    volumes:
      # Make docker client accessible so we can launch containers using host docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
      # - ./dagster/orchestrator/assets/:/opt/dagster/dagster_home/assets/
    networks:
      - dagster_network
    depends_on:
      dagster_postgresql:
        condition: service_healthy
      dagster_assets:
        condition: service_started

  dagster_api:
    build:
      context: ./dagster
      dockerfile: ./api.Dockerfile
      args:
        - PYTHON_VERSION=3.9-slim
    container_name: dagster_api
    expose:
      - "8001"
    ports:
      - "8001:8001"
    environment:
      API_HOME: /opt/api/app
    networks:
      - dagster_network
    volumes:
      - ./dagster/:/opt/dagster/app
    depends_on:
      - dagster_postgresql
      - dagster_assets

  main_api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
      args:
        - PYTHON_VERSION=3.12-slim
    container_name: main_api
    expose:
      - "8000"
    ports:
      - "8000:8000"
    environment:
      API_HOME: /opt/api/app
    networks:
      - dagster_network
    depends_on:
      - dagster_postgresql
      - dagster_assets

  model_api:
    build:
      context: ./modal
      dockerfile: ./Dockerfile
      args:
        - PYTHON_VERSION=3.10-slim
    container_name: model_api
    expose:
      - "8002"
    ports:
      - "8002:8002"
    environment:
      API_HOME: /opt/api/app
    networks:
      - dagster_network
    depends_on:
      - dagster_postgresql
      - dagster_assets

networks:
  dagster_network:
    driver: bridge
    name: dagster_network
