find_similar_paper:
  description: "Find the most similar paper to the user's query and provide a summary."
  steps:
    - "Embed the user's query."
    - "Search for the most similar paper."
    - "Summarize the paper."
  inputs:
    - "User's query"
  outputs:
    - "Paper summary"

generate_pseudocode:
  description: "Search for information in the GitHub repository: {github_repo_url}, Focus on codebase."
  steps:
    - "Retrieve the codebase from the GitHub repository."
    - "Generate pseudocode."
  inputs:
    - "GitHub repository URL"
  outputs:
    - "Pseudocode"