find_similar_paper:
  description: "Find the most similar paper to the user's query and provide a summary."
  steps:
    - "Embed the user's query."
    - "Search for the most similar paper."
    - "Summarize the paper."
  inputs:
    - "User's query"
  outputs:
    - "Paper summary"
